version: '3.8'
services:
    logstash-spblitz:
        image: docker.elastic.co/logstash/logstash:7.9.1
        # build: logstash
        container_name: logstash-spblitz
        volumes:
            - ./logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./logstash-pipelines.yml:/usr/share/logstash/config/pipelines.yml
            - ./logstash-spblitz.conf:/usr/share/logstash/config/logstash-spblitz.conf
            - ./mssql-jdbc-8.4.1.jre11.jar:/usr/share/logstash/logstash-core/lib/jars/mssql-jdbc.jar:ro
        networks:
            - elastic
    mssql-spblitz:
        build: mssql
        container_name: mssql-spblitz
        networks:
            - elastic
        ports:
            - 1443:1433

networks:
    elastic:
        external: true