version: '3.8'
services:
  es-single:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es-single
    environment:
      - node.name=es-single
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es-single
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - xpack.monitoring.elasticsearch.collection.enabled=true
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    depends_on:
      - es-single
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_HOSTS: '["http://es-single:9200"]'
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
    name: elastic