version: '3.8'
services:
  zookeeper-kafka-edge:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper-kafka-edge
    hostname: zookeeper-kafka-edge
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka-edge:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka-edge
    hostname: kafka-edge
    depends_on:
      - zookeeper-kafka-edge
    ports:
      - 9092:9092
      - 29092:29092
      - 9992:9992
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kafka-edge:2181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka-edge:19092,LISTENER_DOCKERHOST://kafka-edge:29092,LISTENER_EXTERNAL://kafka-edge:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka-edge:19092,LISTENER_DOCKERHOST://172.17.0.1:29092,LISTENER_EXTERNAL://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_DOCKERHOST:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'True'
  metricbeat-kafka-edge:
    image: docker.elastic.co/beats/metricbeat:7.9.1
    container_name: metricbeat-kafka-edge
    hostname: metricbeat-kafka-edge
    depends_on:
      - kafka-edge
    command: metricbeat -e -strict.perms=false
    user: root #To read the docker socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./metricbeat-modules.yml:/usr/share/metricbeat/metricbeat-modules.yml
  schema-registry-kafka-edge:
    image: confluentinc/cp-schema-registry:5.5.0
    container_name: schema-registry-kafka-edge
    hostname: schema-registry-kafka-edge
    ports:
    - 8081:8081
    depends_on:
    - kafka-edge
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-kafka-edge
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-edge:19092
      SCHEMA_REGISTRY_MASTER_ELIGIBILITY: 'true'
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
  kafka-edge-rest:
    image: confluentinc/cp-kafka-rest:5.5.0
    container_name: kafka-edge-rest
    hostname: kafka-edge-rest
    ports:
    - 8082:8082
    depends_on:
      - schema-registry-kafka-edge
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka-edge:19092
      KAFKA_REST_SCHEMA_REGISTRY_URL: schema-registry-kafka-edge:8081
      KAFKA_REST_HOST_NAME: kafka-edge-rest
      KAFKA_REST_LISTENERS: http://kafka-edge-rest:8082