version: '3.8'
services:
  kafka-connect-debezium:
    image: debezium/connect:1.2
    container_name: kafka-connect-debezium
    hostname: kafka-connect-debezium
    ports:
     - 8083:8083
    environment:
     - BOOTSTRAP_SERVERS=/172.17.0.1:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses